// Generated by dts-bundle v0.2.0

declare module 'component-builder-typescript-example' {
    export var Module: ng.IModule;
}

declare module example {
	interface IGreeterService {
		greet(name: string);
	}
}

