/// ------------------------------------- ///
/// Automatically generated. DO NOT EDIT. ///
/// ------------------------------------- ///

/// <reference path="../example/example-types.d.ts" />

// Generated by dts-bundle v1.4.4

declare module 'component-builder-typescript-example' {
    export var Module: ng.IModule;
    
}

